#!/bin/bash
# demo_provenance_fail.sh — shows how SLSA L3 + reproducible builds catch this

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  SLSA PROVENANCE & REPRODUCIBLE BUILD VERIFICATION             ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# ── Generate a fake provenance document (what the pipeline CLAIMS) ────────
cat > "$SCRIPT_DIR/build_compromised/provenance.json" << 'EOF'
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "server",
      "digest": { "sha256": "__PLACEHOLDER__" }
    }
  ],
  "predicate": {
    "builder": { "id": "https://github.com/company/go-builder@v1.0.0" },
    "buildType": "https://github.com/actions/go-build@v1",
    "invocation": {
      "configSource": {
        "uri": "git+https://github.com/company/clean_app@refs/heads/main",
        "digest": { "sha1": "abc123def456" },
        "entryPoint": ".github/workflows/build.yml"
      },
      "parameters": {
        "build_command": "go build -o server ."
      }
    },
    "materials": [
      {
        "uri": "git+https://github.com/company/clean_app",
        "digest": { "sha1": "abc123def456" }
      },
      {
        "uri": "pkg:docker/golang@1.22-alpine",
        "digest": { "sha256": "1699c10032ca2..." }
      }
    ]
  }
}
EOF

echo "  [1/4] Provenance document generated by pipeline:"
echo "        build_compromised/provenance.json"
echo "        Builder:  company/go-builder@v1.0.0"
echo "        Command:  go build -o server ."
echo "        Source:   git+github.com/company/clean_app @ abc123def456"
echo ""

# ── Show what SLSA L3 requires ─────────────────────────────────────────────
echo "  [2/4] SLSA Level 3 requirements:"
echo "        ✓ Provenance generated by build PLATFORM (not build script)"
echo "        ✓ Source, builder, and steps cryptographically attested"
echo "        ✓ Builder identity verified (e.g. Sigstore / Fulcio)"
echo "        ✓ No persistent, self-hosted, or mutable build environments"
echo ""
echo "        THE GAP in this pipeline:"
echo "        • Provenance says: 'go build -o server .'"
echo "        • Reality:          go wrapper also compiled /opt/.builder/hook.go"
echo "        • A SLSA L3 platform-generated attestation would record the"
echo "          full build environment — including the runner image contents."
echo "        • The image digest company/go-builder:latest ≠ golang:1.22-alpine"
echo "          and would flag as an unrecognised / untrusted builder."
echo ""

# ── Reproducible build test ────────────────────────────────────────────────
echo "  [3/4] Reproducible build test:"
CLEAN_HASH=$(sha256sum "$SCRIPT_DIR/build_clean/server" 2>/dev/null | cut -d' ' -f1 || echo "NOT FOUND")
BAD_HASH=$(sha256sum "$SCRIPT_DIR/build_compromised/server" 2>/dev/null | cut -d' ' -f1 || echo "NOT FOUND")

echo "        Reference build (official image):  ${CLEAN_HASH:0:48}..."
echo "        CI artifact (runner image):        ${BAD_HASH:0:48}..."
echo ""

if [ "$CLEAN_HASH" = "$BAD_HASH" ]; then
    echo "        Result: PASS — binaries are identical (reproducible)"
else
    echo "        Result: ✗ FAIL — binaries differ"
    echo "               The build was NOT reproducible."
    echo "               This is the RED FLAG: same source, different output"
    echo "               means something in the build environment changed the result."
fi
echo ""

# ── Show what Cosign / binary signing would catch ─────────────────────────
echo "  [4/4] Binary signing gap (Sigstore / Cosign):"
echo "        If the CI pipeline had signed the artifact at upload:"
echo ""
echo "        # Sign with keyless Sigstore:"
echo "        cosign sign-blob --bundle server.bundle ./server"
echo ""
echo "        # Verify at deploy time:"
echo "        cosign verify-blob --bundle server.bundle \\"
echo "            --certificate-identity-regexp 'github.com/company/clean_app' \\"
echo "            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \\"
echo "            ./server"
echo ""
echo "        A signature ties the binary to the OIDC identity of the runner."
echo "        If the runner is a self-hosted or modified image outside GitHub's"
echo "        hosted runners, the OIDC token won't match — verification fails."
echo ""
echo "  SUMMARY: Three independent mechanisms would flag this attack:"
echo "    1. Reproducible builds   → hash mismatch"
echo "    2. SLSA L3 provenance    → unrecognised builder / extra materials"
echo "    3. Cosign / keyless sign → OIDC identity mismatch"
echo ""
